name       : knotifyconfig
version    : 5.92.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.92/knotifyconfig-5.92.0.tar.xz : f7f452e3197886a2afdfaa5a2954d412eb0ae2bc47ce742902765c053239313a
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - kio-devel
    - knotifications-devel
rundeps    :
    - devel :
        - knotifications-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
