name       : knotifyconfig
version    : 5.79.0
release    : 47
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.79/knotifyconfig-5.79.0.tar.xz : 2d111a6b80dab8cfce710440824cd528d2d1ee5194a5d1e467e620e45649cd30
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - kio-devel
    - knotifications-devel
rundeps    :
    - devel :
        - knotifications-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
