name       : knotifyconfig
version    : 5.87.0
release    : 54
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.87/knotifyconfig-5.87.0.tar.xz : f03d30525b7fcdcf81071f647cef66c9306ede76ead6e546edb108f3e4f7a549
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - kio-devel
    - knotifications-devel
rundeps    :
    - devel :
        - knotifications-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
