name       : knotifyconfig
version    : 5.96.0
release    : 62
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/knotifyconfig-5.96.0.tar.xz : a2b9fd0dfbb7cd5b535ceb58788f42823cea2fadf30de4ceb43a9bfb0fe16c25
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - kio-devel
    - knotifications-devel
rundeps    :
    - devel :
        - knotifications-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
