name       : knotifyconfig
version    : 5.44.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/knotifyconfig-5.44.0.tar.xz : 3f85c46c7425c398162afb7de42c53d09cdbfbc7442082042a297b3a6be14204
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
