name       : knotifyconfig
version    : 5.47.0
release    : 15
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/knotifyconfig-5.47.0.tar.xz : 546b099c5257e2d59b92c0350415824754cba9f789d767d160bd2ea54b505b7d
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
