name       : knotifyconfig
version    : 5.36.0
release    : 5
source     :
    - https://download.kde.org/stable/frameworks/5.36/knotifyconfig-5.36.0.tar.xz : 7c2c1717a09ef445ed50053a96e18787eb2118e3d14a81dae3cc6df317f49811
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
