name       : knotifyconfig
version    : 5.72.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/knotifyconfig-5.72.0.tar.xz : c4a3275875305c4c5d6ba0e1103a45ecd51089947c294d9b3f6fb03eea497938
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
optimize   : lto
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
builddeps  :
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
