name       : knotifyconfig
version    : 5.25.0
release    : 1
source     :
    - http://download.kde.org/stable/frameworks/5.25/knotifyconfig-5.25.0.tar.xz : f3e0a3d1217370f8bec645c84730057f17df400fe284c45c2feb89e6820afbca
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
