name       : knotifyconfig
version    : 5.91.0
release    : 58
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.91/knotifyconfig-5.91.0.tar.xz : cedb0993e813f063a14b91b3db13d986a4501a5b8d52dc74992a57d4e0ada51e
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - kio-devel
    - knotifications-devel
rundeps    :
    - devel :
        - knotifications-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
