name       : knotifyconfig
version    : 5.84.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/knotifyconfig-5.84.0.tar.xz : c25fab67f21210cbcd79a8a89fc20f549586ae75df106a07e56a052598b8f2f4
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - kio-devel
    - knotifications-devel
rundeps    :
    - devel :
        - knotifications-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
