name       : knotifyconfig
version    : 5.46.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.46/knotifyconfig-5.46.0.tar.xz : 725212e94f321639e67d04cb240b67429bb0cc8a71e30413da77cda7229d2073
license    :
    - LGPL-2.0
    - LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - solid-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
