name       : knotifyconfig
version    : 5.77.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.77/knotifyconfig-5.77.0.tar.xz : 29ba27263e4b33990685cced7bb2d8288cd3370adda1e1df7335e1cd9d1d5d99
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  : desktop.library
optimize   : lto
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
builddeps  :
    - pkgconfig(libcanberra)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - ki18n-devel
    - kio-devel
    - knotifications-devel
    - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
