name       : knotifyconfig
version    : 5.89.0
release    : 56
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.89/knotifyconfig-5.89.0.tar.xz : 509e16bfa83e4a97cf6f4420ad54ee0e3507dfddf7d2ef9fef65440dbbb53810
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-only
component  : desktop.library
summary    : Configuration dialog for desktop notifications.
description: |
    Configuration dialog for desktop notifications.
optimize   : lto
builddeps  :
    - pkgconfig(libcanberra)
    - kio-devel
    - knotifications-devel
rundeps    :
    - devel :
        - knotifications-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
